# Generated by Django 4.1.4 on 2022-12-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operator_projektu', '0002_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicjatywa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(null=True)),
                ('data_rozpoczecia', models.CharField(max_length=20)),
                ('liczba_miejsc', models.IntegerField(null=True)),
                ('lokalizacja', models.CharField(max_length=250)),
                ('kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operator_projektu.kategoria')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operator_projektu.operatorprojektu')),
            ],
        ),
    ]
