# Generated by Django 4.1.4 on 2022-12-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_projektu', '0003_inicjatywa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numer_tel', models.CharField(max_length=11)),
            ],
        ),
    ]
