# Generated by Django 4.1.4 on 2022-12-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operator_projektu', '0004_uzytkownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uczestnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaakceptowany', models.BooleanField(default=False)),
                ('opis_siebie', models.TextField(null=True)),
                ('cv', models.BinaryField(null=True)),
                ('inicjatywa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operator_projektu.inicjatywa')),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operator_projektu.uzytkownik')),
            ],
        ),
    ]
